#!python3
# processing the json files for CSS codes

import fileinput
import json

def pretty_2D_list(table):
    n=9
    for row in table[n:]:
        print('    n='+str(n)+':\t'+str(row))
        n+=1
#        print(row)
#        print(''.join(str(row)))

def main():
    print('This function exract max [n,k,d] and save d in a 2D array/list with respect to n and k')
    print('Invalid json will be skipped and reported. They exist due to parallel file writing when generating codes on qlab')
    data_folder = "json1"
#    data_folder = "codes" 

    filename_list = "filename-list.txt" #generated by `ls *.json > file`
#    filename_list = "sample-filename-list.txt" #smale test set
    print('data_folder: '+data_folder)
    print('filename_list: '+filename_list)
    count=0
    max_distance_table=[[ 0 for k in range(20)] for n in range(35) ]

    n,k,d=-1,-1,-1
    for line in fileinput.input(filename_list):
#        print(line)
      count +=1
      try:
        with open(data_folder+'/'+ line[:-1],'r') as fjson:
            js = json.load(fjson)
#            print(js)
            n,k,d=js['n'],js['k'],js['d']
            if d > max_distance_table[n][k]:
                max_distance_table[n][k] = d
#            for _key in ['n','k','d']:
#                print([_key,js[_key]])
                
#            print jj['n']
#        break
      except:
          print('invalid json: '+line)
#    print('Done')
#    print(max_distance_table[8:15])
    print('[n,k,d] table')
    pretty_2D_list(max_distance_table)
    print(["total number of files:", count])



def test():
        with open('codes/n15k3d2-x5z7dx3dz2-1.json','r') as fjson:
            print(fjson.read())
            js = json.load(fjson)
            print(js)
            n,k,d=js['n'],js['k'],js['d']
            if d > max_distance_table[n][k]:
                max_distance_table[n][k] = d

#test()
#exit()

main()

    
