init:
	python3 -m venv pymatching-env

#environment operations
#source */bin/activate
#deactivate

#installation and test
#pip install --upgrade pip
#pip install pymatching stim --upgrade
#python3 -m pip install -U pygame
test:
	python3 -m pygame.examples.aliens
